server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ducthanh2212/config-file-test.git
          default-label: main
          clone-on-start: true
  security:
    user:
      name: admin123
      password: admin123      

  